### ISSUE TITLE
How to train nr3d in joint with sr3d

### ISSUE THREAD

**Issue by Baijunjie-me** [referit3d/referit3d#2]
Hi,
I encountered some problems during training nr3d in joint with sr3d. 
1. When I use ScanNet scenes for Nr3d data as scannet file, it has a error.
My commands:
`python train_referit3d.py -scannet-file /repository/baijunjie/data/ScanNet-Nr3d/keep_all_points_00_view_with_global_scan_alignment/keep_all_points_00_view_with_global_scan_alignment.pkl  -referit3D-file /repository/baijunjie/data/Linguistic-data/nr3d.csv --log-dir dir_to_log --n-workers 4 --gpu 6 --augment-with-sr3d /repository/baijunjie/data/Linguistic-data/sr3d.csv`
A error:
`Traceback (most recent call last):
  File "train_referit3d.py", line 62, in <module>
    mean_rgb, vocab = compute_auxiliary_data(referit_data, all_scans_in_dict, args)
  File "/home/baijunjie/program/referit3d/referit3d/in_out/neural_net_oriented.py", line 162, in compute_auxiliary_data
    mean_rgb = mean_color(training_scan_ids, all_scans)
  File "/home/baijunjie/program/referit3d/referit3d/in_out/neural_net_oriented.py", line 48, in mean_color
    color = all_scans[scan_id].color
KeyError: 'scene0155_02'
`

2. When I use ScanNet scenes for Sr3d data,I can't get the performance（37.6%±0.4%） in the paper，The result of my training is 29.0%±0.4%. 
My commands:
`python train_referit3d.py -scannet-file /repository/baijunjie/data/ScanNet-Sr3d/keep_all_points_with_global_scan_alignment/keep_all_points_with_global_scan_alignment.pkl  -referit3D-file /repository/baijunjie/data/Linguistic-data/nr3d.csv --log-dir dir_to_log   --n-workers 4 --gpu 6 --augment-with-sr3d /repository/baijunjie/data/Linguistic-data/sr3d.csv
`

Can you tell me how to train nr3d in joint with sr3d correctly and reproduce the results in the referit3d paper?

Thanks！

**Comment by Samir55** [comment]
Dear @Baijunjie-me,

Sorry for the late reply. I will look into this. Could you share with the config.json.txt file generated in the log folder?

**Comment by Baijunjie-me** [comment]
> Dear @Baijunjie-me,
> 
> Sorry for the late reply. I will look into this. Could you share with the config.json.txt file generated in the log folder?

 @Samir55 
1. The config.json.txt file of the first commands：
`{
    "augment_with_sr3d": "/repository/baijunjie/data/Linguistic-data/sr3d.csv",
    "batch_size": 32,
    "checkpoint_dir": "/repository/baijunjie/ckpt_root/11-08-2020-10-58-27/checkpoints",
    "cluster_pid": null,
    "config_file": null,
    "dgcnn_intermediate_feat_dim": [
        128,
        128,
        128,
        128
    ],
    "experiment_tag": null,
    "fine_tune": false,
    "gpu": "5",
    "graph_out_dim": 128,
    "init_lr": 0.0005,
    "knn": 7,
    "lang_cls_alpha": 0.5,
    "language_fusion": "both",
    "language_latent_dim": 128,
    "log_dir": "/repository/baijunjie/ckpt_root/11-08-2020-10-58-27",
    "max_distractors": 51,
    "max_seq_len": 24,
    "max_test_objects": 88,
    "max_train_epochs": 100,
    "mentions_target_class_only": true,
    "min_word_freq": 3,
    "mode": "train",
    "model": "referIt3DNet",
    "n_gpus": 1,
    "n_workers": 2,
    "obj_cls_alpha": 0.5,
    "object_encoder": "pnet_pp",
    "object_latent_dim": 128,
    "patience": 10,
    "points_per_object": 1024,
    "random_seed": 2020,
    "referit3D_file": "/repository/baijunjie/data/Linguistic-data/nr3d.csv",
    "resume_path": null,
    "s_vs_n_weight": null,
    "save_args": true,
    "scannet_file": "/repository/baijunjie/data/ScanNet-Nr3d/keep_all_points_00_view_with_global_scan_alignment/keep_all_points_00_view_with_global_scan_alignment.pkl",
    "tensorboard_dir": "/repository/baijunjie/ckpt_root/11-08-2020-10-58-27/tb_logs",
    "unit_sphere_norm": false,
    "vocab_file": null,
    "word_dropout": 0.1,
    "word_embedding_dim": 64
}
`
2. The config.json.txt file of the second commands：
`{
    "augment_with_sr3d": "/repository/baijunjie/data/Linguistic-data/sr3d.csv",
    "batch_size": 32,
    "checkpoint_dir": "/repository/baijunjie/ckpt_root/11-08-2020-11-45-42/checkpoints",
    "cluster_pid": null,
    "config_file": null,
    "dgcnn_intermediate_feat_dim": [
        128,
        128,
        128,
        128
    ],
    "experiment_tag": null,
    "fine_tune": false,
    "gpu": "6",
    "graph_out_dim": 128,
    "init_lr": 0.0005,
    "knn": 7,
    "lang_cls_alpha": 0.5,
    "language_fusion": "both",
    "language_latent_dim": 128,
    "log_dir": "/repository/baijunjie/ckpt_root/11-08-2020-11-45-42",
    "max_distractors": 51,
    "max_seq_len": 24,
    "max_test_objects": 88,
    "max_train_epochs": 100,
    "mentions_target_class_only": true,
    "min_word_freq": 3,
    "mode": "evaluate",
    "model": "referIt3DNet",
    "n_gpus": 1,
    "n_workers": 4,
    "obj_cls_alpha": 0.5,
    "object_encoder": "pnet_pp",
    "object_latent_dim": 128,
    "patience": 10,
    "points_per_object": 1024,
    "random_seed": 2020,
    "referit3D_file": "/repository/baijunjie/data/Linguistic-data/nr3d.csv",
    "resume_path": "/repository/baijunjie/ckpt_root/11-08-2020-11-45-42/checkpoints/best_model.pth",
    "s_vs_n_weight": null,
    "save_args": true,
    "scannet_file": "/repository/baijunjie/data/ScanNet-Sr3d/keep_all_points_with_global_scan_alignment/keep_all_points_with_global_scan_alignment.pkl",
    "tensorboard_dir": "/repository/baijunjie/ckpt_root/11-08-2020-11-45-42/tb_logs",
    "unit_sphere_norm": false,
    "vocab_file": null,
    "word_dropout": 0.1,
    "word_embedding_dim": 64`
}

**Comment by Samir55** [comment]
1.  In the joint training, as mentioned  in [ScanNet instructions](https://github.com/referit3d/referit3d/blob/eccv/referit3d/data/scannet/README.md)  you should use all ScanNet scans (not just the ones ending with the _00), so you should create a new ScanNet.pkl file having all the scans (including _01, _02, etc). To do so, you should rerun prepare_scannet_data.py with adding the following argument:
```
-process-only-zero-view false

python prepare_scannet_data.py -top-scan-dir path_to_scans_dir -top-save-dir save_dir  -process-only-zero-view false
```

2. For joint training please set s_vs_n_weight to 0.4 and batch size to 64 (that's what we used to get our results - really sorry for leaving this undocumented). I.e., please pass the following argument when you train jointly:
```Console
--s-vs-n-weight 0.4 --batch-size 64
```
