### ISSUE TITLE
Missing file glove.6B.100d.vocabulary.txt

### ISSUE THREAD

**Issue by CurryYuan** [referit3d/referit3d#3]
And there are bugs in prepare_referential_data.py.

**Comment by Samir55** [comment]
Dear @CurryYuan, 

Sorry for the late reply, I will look into this.

**Comment by rohjunha** [comment]
I have resolved this issue by providing the glove.6B.100d file (from http://nlp.stanford.edu/data/glove.6B.zip) to the required path.
